sudo: true
dit: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
        - docker build -t protobuf-go .
        - docker images
        - docker tag protobuf-go $DOCKER_LOGIN/protobuf-go
        - docker push $DOCKER_LOGIN/protobuf-go
